/**
 * Public surface of src/api for seam C. See spec section 5: seam C
 * "imports the API only through ui/src/api, whose surface is fixed in
 * §5.4 and §5.5" — this barrel is that surface, plus the token actions
 * `useModel.ts` adds out of necessity (see that file's header comment).
 */
export type {
  Capability,
  CollectorStatus,
  ConfigFPPEndpoint,
  ConfigFPPEndpointsPayload,
  ConfigRevisionMeta,
  ConfigRevisionsResponse,
  ConnectionState,
  ControlPlane,
  DiscoveryProposal,
  DiscoveryRun,
  Evidence,
  EvidenceState,
  Event,
  EventSeq,
  FPPEndpointsConfigResponse,
  FPPCommandResult,
  // Track G seam G-2 (ADR-039).
  ConfigResolumeInstance,
  ConfigResolumeInstancesPayload,
  ResolumeInstancesConfigResponse,
  // Track G seam G-3 (ADR-039).
  ConfigFPPMQTTPayload,
  ConfigFPPMQTTPutRequest,
  FPPMQTTConfigResponse,
  // Track G seam G-4 (ADR-039).
  AssetsSettingsConfigResponse,
  ConfigAssetsSettingsPayload,
  ConfigAssetsSettingsPutPayload,
  FPPInstance,
  // The pending-instanceUuid-change acknowledgement.
  FPPInstanceUUIDChange,
  AcknowledgeFPPInstanceUUIDChangeResponse,
  Model,
  Node,
  NodeDeclaration,
  NodeEvidence,
  PrincipalSummary,
  // Track G seam G-5: identity administration over the API.
  PrincipalObject,
  PrincipalsResponse,
  PrincipalResponse,
  CreatePrincipalRequest,
  SetPrincipalRoleRequest,
  SetPrincipalPasswordRequest,
  TokenObject,
  TokensResponse,
  IssueTokenRequest,
  IssueTokenResponse,
  ResolumeCompositionResponse,
  ResolumeCompositionSummary,
  ResolumeCompositionUploadResponse,
  ResolumeRecoveryRecordEntry,
  ResolumeRecoveryRestoreLayer,
  ResolumeRecoveryRestoreReport,
  ResolumeRecoveryResponse,
  ResolumeRecoveryRestoreResponse,
  ConfigResolumeRecoveryPayload,
  ResolumeRecoveryConfigResponse,
  // Track B seam B2c (ADR-039): render.settings.
  ConfigRenderRestartPolicy,
  ConfigRenderSettingsPayload,
  RenderSettingsConfigResponse,
  // ADR-033: the installation-wide operating mode.
  ConfigShowModePayload,
  ShowModeConfigResponse,
  // Track B seam B2b-front: the three render.* dispatch endpoints.
  ObservationEntry,
  RenderCommandResult,
  // The first audio-dispatch slice: pause/resume/stop/output.mute/output.unmute.
  AudioSessionCommandResult,
  // Track D seam D-4: Resolume as an observability resource and the
  // seven-action vocabulary.
  ResolumeInstanceComposition,
  ResolumeInstance,
  ResolumeInstancesResponse,
  ResolumeInstanceResponse,
  ResolumeActionParam,
  ResolumeAction,
  ResolumeActionsResponse,
  ResolumeActionResult,
  ResolumeActionResponse,
  // The pre-show binding check and one action invocation, outside of any
  // macro run (ADR-029).
  ActionBinding,
  ActionInvocationResult,
  ResolumeCompositionDeckSummary,
  ResolumeCompositionLayerGroup,
  ResolumeCompositionLayer,
  ResolumeCompositionColumn,
  ResolumeCompositionClip,
  ResourceRef,
  SessionInfo,
  SessionResponse,
  StreamSeq,
  // `GET /` (getServiceDescriptor): the coordinator's own build metadata.
  ServiceDescriptor,
  CoordinatorInfo,
  // Step 9 (STEP-9-SPEC.md sections 5, 6): show.action / show.macro
  // configuration objects and the macro run surface.
  ConfigObjectSummary,
  ConfigObjectsListResponse,
  // Finding 16: show.surface reads, so the UI can discover a
  // configured-but-not-yet-applied surface the way showmeshctl already can.
  ConfigShowSurface,
  ShowSurfaceConfigResponse,
  // Track H seam H6: show.cue authoring.
  ConfigShowCueRenderOutput,
  ConfigShowCueAudioOutput,
  ConfigShowCueLTCOutput,
  ConfigShowCueAnnouncementOutput,
  ConfigShowCueOutputs,
  ConfigShowCue,
  ShowCueConfigResponse,

  // Track H seam H6: show.playlist authoring.
  ConfigShowPlaylistFPPBinding,
  ConfigShowPlaylistShowmeshAudio,
  ConfigShowPlaylistEntryFPP,
  ConfigShowPlaylistEntry,
  ConfigShowPlaylist,
  ShowPlaylistConfigResponse,
  ConfigShowActionMQTTPublish,
  ConfigShowActionMQTTExpect,
  ConfigShowActionTarget,
  ConfigShowAction,
  ShowActionConfigResponse,
  ConfigShowMacroLocalFallback,
  ConfigShowMacroStep,
  ConfigShowMacro,
  ShowMacroConfigResponse,
  MacroRunSummary,
  MacroRunStepCommand,
  MacroRunStep,
  MacroRun,
  MacroRunResponse,
  MacroRunSubmitResponse,
  MacroRunsListResponse,
  MacroPriorFailureRequest,
  CreateMacroRunRequest,
  MacroRunChangedEvent,
  // Track G seam G-8: the Operator UI for Track E (ADR-027, ADR-026,
  // ADR-028).
  ConfigShow,
  ConfigShowWrite,
  ShowConfigResponse,
  ConfigShowSurfaceChannelRange,
  ConfigShowSurfaceGeometry,
  ConfigShowSurfaceNDIOutput,
  ConfigShowSurfaceHDMI,
  ConfigShowSurfaceOutput,
  ConfigShowActive,
  ShowActiveConfigResponse,
  Asset,
  AssetResponse,
  AssetsListResponse,
  NodeAssetManifest,
  MissingAsset,
  AssetGap,
  ExtraAsset,
  NodeAssetManifestResponse,
  AssetManifestResponse,
  AuditEntry,
  AuditResponse,
  // Track H seam H6: the resolved Cue catalog a node holds, and the
  // deploy dispatch's own result shape.
  CueCatalogResponse,
  CueCatalogEntry,
  CueCatalogDeployResult,
  // Track F seam F2/F1: the night-session lifecycle controller and the
  // night.session/night.session.active configuration kinds.
  ConfigNightSessionFPPPlaylist,
  ConfigNightSessionAssetRef,
  ConfigNightSessionBackgroundAudioItem,
  ConfigNightSessionBackgroundAudio,
  ConfigNightSessionResting,
  ConfigNightSessionCue,
  ConfigNightSessionEnterShow,
  ConfigNightSessionEnterResting,
  ConfigNightSessionCueWrite,
  ConfigNightSessionEnterShowWrite,
  ConfigNightSessionEnterRestingWrite,
  ConfigNightSessionBackgroundAudioWrite,
  ConfigNightSessionRestingWrite,
  ConfigNightSessionWrite,
  ConfigNightSession,
  NightSessionConfigResponse,
  ConfigNightSessionActive,
  NightSessionActiveConfigResponse,
  NightReadinessCheck,
  NightReadiness,
  NightPhaseEvidence,
  NightCue,
  NightCues,
  NightBackgroundAudioStep,
  NightBackgroundAudio,
  NightAuthorization,
  NightSessionState,
  NightSessionResponse,
  NightCommandRequest,
  NightCommandResult,
  NightCommandResponse,
  NightSessionChangedEvent,
  NightCommandName,
  // TRACK-H-H2-SPEC.md §5/§6: the two read-only FPP playlist show-night
  // verdicts.
  FPPPlaylistReadinessResponse,
  FPPPlaylistEntryReconciliationResponse,
} from './domain'
export {
  useModel,
  submitToken,
  clearToken,
  login,
  logout,
  claimBootstrap,
  getServiceDescriptor,
  getFPPEndpointsConfig,
  putFPPEndpointsConfig,
  getFPPEndpointsConfigRevisions,
  listFPPPlaylistEntryObservations,
  deleteFPPPlaylistEntryObservation,
  acknowledgeFPPInstanceUUIDChange,
  getFPPPlaylistReadiness,
  getFPPPlaylistEntryReconciliation,
  getResolumeInstancesConfig,
  putResolumeInstancesConfig,
  getResolumeInstancesConfigRevisions,
  getFPPMQTTConfig,
  putFPPMQTTConfig,
  getFPPMQTTConfigRevisions,
  getAssetsSettingsConfig,
  putAssetsSettingsConfig,
  getAssetsSettingsConfigRevisions,
  stopFPPPlaylist,
  startFPPPlaylist,
  stopFPPPlaylistGracefully,
  pauseFPPPlaylist,
  resumeFPPPlaylist,
  nextFPPPlaylistItem,
  prevFPPPlaylistItem,
  setFPPVolume,
  applyRenderSurface,
  clearRenderSurface,
  restartRenderPipeline,
  pauseAudioSession,
  resumeAudioSession,
  stopAudioSession,
  muteAudioSessionOutput,
  unmuteAudioSessionOutput,
  prepareAudioSession,
  startAudioSession,
  advanceAudioSession,
  clearAudioSession,
  seekAudioSession,
  setAudioSessionGain,
  fadeAudioSessionGain,
  applyAudioSession,
  probeRenderTransport,
  runDiscovery,
  declareNode,
  deleteNodeDeclaration,
  listConfigObjects,
  listShowSurfacesForNode,
  getShowSurface,
  getShowPlaylist,
  putShowPlaylist,
  getShowPlaylistRevisions,
  getShowAction,
  putShowAction,
  getShowActionRevisions,
  getActionBinding,
  listActionBindings,
  invokeAction,
  getShowMacro,
  putShowMacro,
  getShowMacroRevisions,
  submitMacroRun,
  listMacroRuns,
  getMacroRun,
  getResolumeComposition,
  uploadResolumeComposition,
  getResolumeRecovery,
  getResolumeRecoveryConfig,
  putResolumeRecoveryConfig,
  getResolumeRecoveryConfigRevisions,
  restoreResolumeRecovery,
  getRenderSettingsConfig,
  putRenderSettingsConfig,
  getRenderSettingsConfigRevisions,
  getShowModeConfig,
  putShowModeConfig,
  getShowModeConfigRevisions,
  listResolumeInstances,
  getResolumeInstance,
  listResolumeActions,
  launchResolumeClip,
  clearResolumeLayer,
  launchResolumeColumn,
  selectResolumeDeck,
  blackoutResolume,
  setResolumeLayerBypass,
  setResolumeLayerMaster,
  listPrincipals,
  createPrincipal,
  setPrincipalRole,
  disablePrincipal,
  enablePrincipal,
  resetPrincipalPassword,
  listPrincipalTokens,
  issuePrincipalToken,
  revokePrincipalToken,
  // Track G seam G-8: the Operator UI for Track E.
  getShow,
  putShow,
  getShowRevisions,
  putShowSurface,
  getShowSurfaceRevisions,
  // Track H seam H6: show.cue authoring.
  getShowCue,
  putShowCue,
  getShowCueRevisions,
  getShowActive,
  putShowActive,
  getShowActiveRevisions,
  listAssets,
  uploadAsset,
  assetContentUrl,
  getAssetManifest,
  getNodeAssetManifest,
  listAudit,
  // Track H seam H6: the resolved Cue catalog a node holds and the
  // operator's own deploy control.
  getNodeCueCatalog,
  deployNodeCueCatalog,
  // Track F seam F2/F1: the night-session lifecycle controller and the
  // night.session/night.session.active configuration kinds.
  getCurrentNightSession,
  getNightSessionById,
  dispatchNightCommand,
  getNightSessionConfig,
  putNightSessionConfig,
  getNightSessionConfigRevisions,
  getNightSessionConfigRevision,
  getNightSessionActiveConfig,
  putNightSessionActiveConfig,
  getNightSessionActiveConfigRevisions,
} from './useModel'

// Track D seam D-2a: the progress shape [uploadResolumeComposition]'s
// callback reports — a type-only export, unlike everything above, since
// no runtime value of this shape is ever constructed inside src/api
// itself (the component that calls uploadResolumeComposition builds and
// reads it).
export type { UploadProgress } from './resolumeCompositionUpload'

// A pure, side-effect-free read of whether a break-glass token is
// currently stored (token.ts) — exported so SessionPanel.tsx can decide
// whether to offer clearing one directly, without reaching past this
// barrel into an internal module. Not a store action (no ApiStore
// singleton involved) and not itself part of ADR-022 decision 4's
// storage contract, which stays owned by token.ts.
export { getStoredToken } from './token'

// Exported for seam C's error-boundary / advanced testing needs and for
// this seam's own tests; the real application only ever needs the
// singleton wired up in useModel.ts.
export { ApiStore, createApiStore, type ApiStoreOptions } from './store'

// ADR-024's typed request errors: seam C's sign-in/sign-out/bootstrap
// forms (login/logout/claimBootstrap above all reject with one of these)
// need to dispatch on error TYPE to render the right message — "wrong
// password" (UnauthorizedError), "your browser can't do this, use the
// token field" (CSRFRejectedError), "you don't hold that scope"
// (ForbiddenError), "slow down" (TooManyRequestsError) — never on message
// text, matching this API's own "dispatch on type, never title/detail"
// posture (problem.ts).
export {
  ApiError,
  CSRFRejectedError,
  ForbiddenError,
  IncompatibleVersionError,
  TooManyRequestsError,
  UnauthorizedError,
} from './errors'
